[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
social_linking = "B6Zx3sv8tRUHJq3pzLSfikCd6uEx17ksp6FmyEoeh1Wd"

[programs.devnet]
social_linking = "B6Zx3sv8tRUHJq3pzLSfikCd6uEx17ksp6FmyEoeh1Wd"

[programs.mainnet]
social_linking = "B6Zx3sv8tRUHJq3pzLSfikCd6uEx17ksp6FmyEoeh1Wd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
